UPDATE_ZSH_DAYS=10
DISABLE_UNTRACKED_FILES_DIRTY="false"
COMPLETION_WAITING_DOTS=" %F{yellow}waiting... "
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="true"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="false"
CASE_SENSITIVE="false"
HIST_STAMPS="dd.mm.yyyy"
ZSH_AUTOSUGGEST_STRATEGY=(completion) 
ZSH_THEME="starship"




